{"ast":null,"code":"/**\r\n * Higher-order function for async/await error handling\r\n * @param {function} fn an async function\r\n * @returns {function}\r\n */\nexport const catchErrors = fn => {\n  return function () {\n    return fn(...arguments).catch(err => {\n      console.error(err);\n    });\n  };\n};","map":{"version":3,"sources":["C:/Users/Mike/my-app/client/src/utils.js"],"names":["catchErrors","fn","catch","err","console","error"],"mappings":"AAAA;AACA;AACA;AACA;AACA;AACC,OAAO,MAAMA,WAAW,GAAGC,EAAE,IAAI;AAC9B,SAAO,YAAkB;AACvB,WAAOA,EAAE,CAAC,YAAD,CAAF,CAAYC,KAAZ,CAAmBC,GAAD,IAAS;AAChCC,MAAAA,OAAO,CAACC,KAAR,CAAcF,GAAd;AACD,KAFM,CAAP;AAGD,GAJD;AAKD,CANK","sourcesContent":["/**\r\n * Higher-order function for async/await error handling\r\n * @param {function} fn an async function\r\n * @returns {function}\r\n */\r\n export const catchErrors = fn => {\r\n    return function(...args) {\r\n      return fn(...args).catch((err) => {\r\n        console.error(err);\r\n      })\r\n    }\r\n  }\r\n\r\n  "]},"metadata":{},"sourceType":"module"}